### ISSUE TITLE
heroku deployment not working

### ISSUE THREAD

**Issue by RudranBera** [KiraLT/torrent-stream-server#296] opened 2021-11-27 07:46 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by KiraLT** [comment] 2021-12-21 10:06
Duplicate of #286

**Closed by KiraLT** 2021-12-21 10:06 UTC
Labels: duplicate
