### ISSUE TITLE
All categories search returns invalid

### ISSUE THREAD

**Issue by aiden9723** [KiraLT/torrent-stream-server#164] opened 2021-06-08 08:06 UTC
When searching 1337x under all categories the search returns invalid and only works when the specific category is selected this has occurred since v1.7.0 .

**Comment by KiraLT** [comment] 2021-06-08 08:32
The issue is resolved in [v1.7.2](https://github.com/KiraLT/torrent-stream-server/releases/tag/v1.7.2) release

**Closed by KiraLT** 2021-06-08 08:32 UTC
